# Generated by Django 4.0 on 2021-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listrequestdetail',
            name='phone_number',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
